[package]
name = "simple_regex"
version = "0.1.0"
authors = ["Sune Kirkeby <ski@csis.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
